### ISSUE TITLE
run a demo with a single image

### ISSUE THREAD

**Issue by Kenneth-X** [visinf/1-stage-wseg#10]
hi, fantastic work !
 i want to run a demo with a single image by using infer_val.sh and model_enc_e020Xs0.928.pth ， how can i set the FILELIST, EXP, SNAPSHOT and RUN_ID

**Comment by betogulliver** [comment]
did you get it to test with a single image? 
do you need to provide the "SegmentationClass" image too?
(my notes here below)

thanks for any/all help.

---------------------------------------
I see we can simple edit/modify

./data/val_voc.txt --> ./data/val_mydata.txt

    mydata/JPEGImages/001.jpg mydata/SegmentationClass/001.png
    ...

and set
FILELIST=./data/val_mydata.txt

However './data/val_voc.txt' requires (and is used by 'infer_val.py") "SegmentationClas"

Do I need to provide de 'SegmentationClass' image too?
--------------------------------------

**Comment by Kenneth-X** [comment]
> did you get it to test with a single image?
> do you need to provide the "SegmentationClass" image too?
> (my notes here below)
> 
> thanks for any/all help.
> 
> I see we can simple edit/modify
> 
> ./data/val_voc.txt --> ./data/val_mydata.txt
> 
> ```
> mydata/JPEGImages/001.jpg mydata/SegmentationClass/001.png
> ...
> ```
> 
> and set
> FILELIST=./data/val_mydata.txt
> 
> However './data/val_voc.txt' requires (and is used by 'infer_val.py") "SegmentationClas"
> 
> ## Do I need to provide de 'SegmentationClass' image too?

> 

please reference this code:

> https://github.com/visinf/1-stage-wseg/blob/c5651b1f95f87dafc8ed44d9631139062433d9b5/datasets/pascal_voc_ms.py#L19

if you do not want to modify this code ,you need to provide 'SegmentationClass' image to match the 'val_voc.txt' format
but if you only want to test a single a image , i suggest you to modify this code，here is my code, which is the voc test format:
```
2008_000006
2008_000011
2008_000024
2008_000056
```

```
def load_img_name_list(dataset_path, index='.jpg'):

    img_gt_name_list = open(dataset_path).read().splitlines()
    img_name_list = [img_gt_name+index for img_gt_name in img_gt_name_list]

    return img_name_list

def load_label_name_list(dataset_path):
    return load_img_name_list(dataset_path, '.png')
```

**Comment by betogulliver** [comment]
thanks for your prompt reply.
sure I can modify 'pascal_voc_ms.py' according to your directions,

but, it seems, I still need to provide the ".png" (SegmentationClass" images, am I wrong?

thanks in advance

**Comment by Kenneth-X** [comment]
sure ,you need the png file, which will be return in :

> https://github.com/visinf/1-stage-wseg/blob/c5651b1f95f87dafc8ed44d9631139062433d9b5/datasets/pascal_voc_ms.py#L146

**Comment by Kenneth-X** [comment]
if you do not care gt ,which will be display in 

> https://github.com/visinf/1-stage-wseg/blob/master/utils/inference_tools.py#L67

you can use whatever png you want or just a black image

**Comment by betogulliver** [comment]
using a "dummy" pallete-index image throws the following error

# Not Good!
dummy = Image.new("P", (100, 100), color=0) 

# OK
dummy = Image.open("2007_000033.png") # random "SegmenataionClass" image from original VOC dataset

```
(1-stage-wseg) user@machine% bash launchinfer_val.py

Saving to: out/pascal_voc/nikon/v01/nikon_val_voc
python infer_val.py --dataset pascal_voc --cfg configs/nikon_voc_resnet38.yaml --exp nikon --run v01 --resume e020Xs0.928 --infer-list data/nikon_val_voc.txt --workers 6 --mask-output-dir out/pascal_voc/nikon/v01/nikon_val_voc
Backbone: ResNet38
Model: AE
Loading weights from:  ./models/weights/ilsvrc-cls_rna-a1_cls1000_ep-0001.pth
File not found:  ./snapshots/pascal_voc/nikon/v01/opt_enc_e020Xs0.928.pth
Inference batch size:  4
  0%|                                                                                                                                                         | 0/20 [00:00<?, ?it/s]Traceback (most recent call last):
  File "infer_val.py", line 91, in <module>
    for iter, (img_name, img_orig, images_in, pads, labels, gt_mask) in enumerate(tqdm(dataloader)):
  File "/home/user/anaconda3/envs/1-stage-wseg/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1022, in __iter__
    for obj in iterable:
  File "/home/user/anaconda3/envs/1-stage-wseg/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/user/anaconda3/envs/1-stage-wseg/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/home/user/anaconda3/envs/1-stage-wseg/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/user/anaconda3/envs/1-stage-wseg/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/user/work/projects/nikon/2020.07.01/code/03-1-stage-wseg/datasets/pascal_voc_ms.py", line 124, in __getitem__
    name, img, label, mask = super().__getitem__(im_idx)
  File "/home/user/work/projects/nikon/2020.07.01/code/03-1-stage-wseg/datasets/pascal_voc_ms.py", line 93, in __getitem__
    assert unique_labels.size > 0, 'No labels found in %s' % self.masks[index]
AttributeError: 'MultiscaleLoader' object has no attribute 'masks'
(1-stage-wseg) user@machine%
```

**Comment by betogulliver** [comment]
this fixed my problem. thanks for all your help

```python
dummy = Image.new("P", (100, 100), color=0) # pallete (indexed)
dummy.putpixel((0, 0), 1) # 1-pixel 'person' mask! # you need this!

```
