### ISSUE TITLE
what is "opt_enc_xxx" ??

### ISSUE THREAD

**Issue by Kenneth-X** [visinf/1-stage-wseg#11]
hi, i successfully  load the model, but in checkpoint.py there are such bugs:

python infer_val.py --dataset pascal_voc --cfg configs/voc_resnet38.yaml --exp baselines --run v01 --resume e020Xs0.928 --infer-list data/val_voc.txt --workers 6 --mask-output-dir ./output/
['--dataset', 'pascal_voc', '--cfg', 'configs/voc_resnet38.yaml', '--exp', 'baselines', '--run', 'v01', '--resume', 'e020Xs0.928', '--infer-list', 'data/val_voc.txt', '--workers', '6', '--mask-output-dir', './output/']
{'MODEL': 'ae', 'BACKBONE': 'resnet38', 'PRE_WEIGHTS_PATH': './models/weights/model_enc_e020Xs0.928.pth', 'OPT': 'SGD', 'LR': 0.001, 'BETA1': 0.5, 'MOMENTUM': 0.9, 'WEIGHT_DECAY': 0.0005, 'LOSS': 'SoftMargin', 'MASK_LOSS_BCE': 1.0, 'BG_SCORE': 0.1, 'FOCAL_P': 3, 'FOCAL_LAMBDA': 0.01, 'PAMR_KERNEL': [1, 2, 4, 8, 12, 24], 'PAMR_ITER': 10, 'SG_PSI': 0.3}
Backbone: ResNet38
Model: AE
Loading weights from:  ./models/weights/model_enc_e020Xs0.928.pth
File not found__:  ./snapshots/pascal_voc/baselines/v01/opt_enc_e020Xs0.928.pth

**Comment by arnike** [comment]
Hi @Kenneth-X,
this file stores the state of the optimiser and is not needed at test time. So, just ignore this warning.
Best,
Nikita
