### ISSUE TITLE
Cannot reproduce the results of the paper

### ISSUE THREAD

**Issue by DesertsP** [visinf/1-stage-wseg#16]
I use code in this repository to train on my machine, using the default parameters and configuration. The only difference is that I used 2080Ti, so I switched to PyTorch 1.3.1 and CUDA 10.0, because version 1.0 will cause "CUDA out of memory error".

My result: 
miou: 0.585
with CRF 0.6007

**Comment by loserbbb** [comment]
So do I, my best result is 0.5821(with CRF)

**Comment by arnike** [comment]
Hi @DesertsP,
thanks for your feedback! A few questions: From which epoch did you get this model? Is this the best score across a few runs, or from a single run? Which commit did you use? I don't have the capacity right now to try and reporoduce your enivronment, but I'd agree it shouldn't matter much. There may be some +/- between the runs, which most weakly supervised methods suffer from, as far as I know. However, the difference esp. with CRF looks quite significant. In my experience, however, small changes in the IoU w/o CRF can make a significant change to the IoU with CRF.

@loserbbb, I suspect that something else might be going wrong in your case, as the IoU you get is way too small. But I would need more details about your setup to understand.

Best,
Nikita

**Comment by loserbbb** [comment]
Hello, thank you for your reply. I don't have a multi-GPU environment, the best result from an experiment on a single V100. Therefore, I set the Batch size to a lower value and set it to 10, with pytorch1.2, cuda10.1. I choose the snapshot with the highest score when inference, the epoch was 14. I also tested it on other machines, such as Titan xp. The lowest score was less than 0.5. The common difference is that the epoch is modified and the pytorch version is high. (All the scores I mentioned are using CRF) @arnike

**Comment by DesertsP** [comment]
Hi, Nikita. Thanks for your reply. I trained many times with different seeds, and selected the best from different checkpoints, and finally mIoU reached the result in the paper.

(I use 2xV100 16G and pytorch 1.2 this time.)
Thank you for doing such a good job.

**Comment by xzz2** [comment]
> Hi, Nikita. Thanks for your reply. I trained many times with different seeds, and selected the best from different checkpoints, and finally mIoU reached the result in the paper.
> 
> (I use 2xV100 16G and pytorch 1.2 this time.)
> Thank you for doing such a good job.

Can you please tell me the vaule of seed to get the same result as the paper? Thank you!

**Comment by DesertsP** [comment]
@xzz2 I set 128 and train 13 epochs

**Comment by xzz2** [comment]
@DesertsP Thanks a lot! I will try it.

**Comment by arnike** [comment]
@loserbbb 1) The results are expected to deviate if trained with a different batch size. 2) The reported results are from training on 2 TITAN X GPUs, but I agree that it shouldn't make a difference if trained on a single GPU (provided no change to the training parameters). 3) Note that the current criterion for checkpointing (val loss) _is only a proxy score_ for the IoU. In my setup, I consistently observed highest IoU at epoch 20, which coincided with the optimum of the proxy score, hence the results are reported for a 20-epoch training (including the 5-epoch pre-training).
@DesertsP Thanks.
