### ISSUE TITLE
trainloader problem

### ISSUE THREAD

**Issue by muhammetaslan** [visinf/1-stage-wseg#18]
When ı start the training process, this error occurs. Could you give me any suggestions?

I have a single Tesla V100 GPU (16GB).

"
File "train.py", line 49, in __init__
self.denorm = self.trainloader.dataset.denorm
AttributeError: 'DecTrainer' object has no attribute 'trainloader'
"

**Comment by hyalvin** [comment]
It means that there is no attribute named 'trainloader' in the class DecTrainer, I think you may have removed some code carelessly,  please check whether this line `self.trainloader = get_dataloader(args, cfg, 'train')` still exists, it lies in line 45 in my code.
