### ISSUE TITLE
problem with test config

### ISSUE THREAD

**Issue by Khanhnn00** [visinf/1-stage-wseg#21]
Hello authors,
thanks for your dedicated work. However, I am currently confused with the FLIP and SCALES options in testing phase. I do not understand how it affects my final result, because I'm running on a single test image only.  Do I have to keep the default config? I'm setting it as False in FLIP and only 1 in SCALES only, and the results on random images indicates it does not much differ from your default config.

Thanks in advance.

**Comment by arnike** [comment]
Hi @Khanhnn00,
these settings are for _multi-scale inference_, which is standard in this domain. `SCALES` specifies the scaling factor, while `FLIP` indicates if the images should be flipped. For example if `SCALES: [1, 0.5, 1.5, 2.0]` and `FLIP: True`, at inference time the network gets a batch with **8** versions of the same image (four scales + four scales flipped). The final prediction is a merge of the predictions from this batch.
Please, do look in the code if you change the number of scales or disable flipping, as these settings are not "plug-and-play"  in the current implementation, which expects this multi-scale setup.

Best,
Nikita
