### ISSUE TITLE
how to output cam map in infer_val.py

### ISSUE THREAD

**Issue by liz6688** [visinf/1-stage-wseg#7]
Hi,
Thanks for sharing your  work. 
But, I have a problem. How to output and visualize cam map of each class in the infer_val.py.  
Hope your reply. 
Thanks.

**Comment by arnike** [comment]
Hi @liz6688,
CAMs are only produced for the baseline models, because our method does not have CAMs. It predicts the semantic maps directly. This is done automatically by infer_val.py (it saves the visualisation in the directory your specify).
Hope this answers your question.
