### ISSUE TITLE
Error encountered while launching from shell 

### ISSUE THREAD

**Issue by bangawayoo** [visinf/1-stage-wseg#8]
Hi, thank you for sharing your implementation.

I am trying to run the code on a machine with CUDA 10.2 due to the graphic card requirements. 
When following the instructions for running ./launch/run_voc_resnet101.sh, I constantly have this error after the model is instantiated : 

> Group 0: #103, LR=1.000e-03
Group 1: #0, LR=1.000e-03
Group 2: #26, LR=1.000e-02
Group 3: #13, LR=1.000e-02
Using SGD >>> learning rate = 1.000e-03, momentum = 9.000e-01, weight decay = 5.000e-04
Epoch >>>  0
/home/ky/Desktop/Project/BabyMind/1-stage-wseg/core/config.py:123: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  yaml_cfg = AttrDict(yaml.load(f))
Traceback (most recent call last):
  File "train.py", line 334, in <module>
    time_call(trainer.validation, "Validation / Train: ", epoch, trainer.writer, trainer.trainloader_val)
  File "train.py", line 324, in time_call
    func(*args, **kwargs)
  File "train.py", line 245, in validation
    for n, (image, gt_labels, _) in enumerate(loader):
  File "/home/ky/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/ky/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/ky/.local/lib/python3.6/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ky/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ky/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ky/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ky/Desktop/Project/BabyMind/1-stage-wseg/datasets/pascal_voc.py", line 175, in __getitem__
    labels[unique_labels] = 1
IndexError: The shape of the mask [2] at index 0does not match the shape of the indexed tensor [20] at index 0

All the other libraries follow the required versions, except CUDA. I am not sure if this is a CUDA version error. I am wondering if you have encountered this error before.
Any suggestions in fixing this would be a great help.

Thank you in advance.

Best regards,
KiYoon

**Comment by arnike** [comment]
Hi @bangawayoo,
I don't think it's related to CUDA. The error points to "datasets/pascal_voc.py", line 175, which could due to a different numpy version or different labelling format of your data. What this line does is to create a 0/1 label vector which indicates presence of a category in the image. It does so with an index array, which in your case seems not to work. What's your numpy version? What are the contents of unique_labels when this happens?
Best,
Nikita

**Comment by bangawayoo** [comment]
Hi,
Thank you for your reply. 
My numpy version is 1.15.4 as required. Unfortunately I was not able to pinpoint the problem, but I was able to work around the problem by running the train.py script instead after manually fixing the arguments for opt.py

**Comment by SomeoneDaniel** [comment]
I met a similar issue with running the script 'run_voc_resnet38.sh'. 

Traceback (most recent call last):
  File "G:/Projects/1-stage-wseg/train.py", line 334, in <module>
    time_call(trainer.validation, "Validation / Train: ", epoch, trainer.writer, trainer.trainloader_val)
  File "G:/Projects/1-stage-wseg/train.py", line 324, in time_call
    func(*args, **kwargs)
  File "G:/Projects/1-stage-wseg/train.py", line 245, in validation
    for n, (image, gt_labels, _) in enumerate(loader):
  File "C:\Users\xxx\AppData\Local\Continuum\anaconda2\envs\torch_gpu\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
Warning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (expandTensors at C:\w\1\s\tmp_conda_3.6_095855\conda\conda-bld\pytorch_1579082406639\work\aten\src\ATen/native/IndexingUtils.h:20)
    data = self._next_data()
  File "C:\Users\xxx\AppData\Local\Continuum\anaconda2\envs\torch_gpu\lib\site-packages\torch\utils\data\dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "C:\Users\xxx\AppData\Local\Continuum\anaconda2\envs\torch_gpu\lib\site-packages\torch\utils\data\dataloader.py", line 881, in _process_data
    data.reraise()
  File "C:\Users\xxx\AppData\Local\Continuum\anaconda2\envs\torch_gpu\lib\site-packages\torch\_utils.py", line 394, in reraise
Warning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (expandTensors at C:\w\1\s\tmp_conda_3.6_095855\conda\conda-bld\pytorch_1579082406639\work\aten\src\ATen/native/IndexingUtils.h:20)
Warning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (expandTensors at C:\w\1\s\tmp_conda_3.6_095855\conda\conda-bld\pytorch_1579082406639\work\aten\src\ATen/native/IndexingUtils.h:20)
Warning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (expandTensors at C:\w\1\s\tmp_conda_3.6_095855\conda\conda-bld\pytorch_1579082406639\work\aten\src\ATen/native/IndexingUtils.h:20)
Warning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (expandTensors at C:\w\1\s\tmp_conda_3.6_095855\conda\conda-bld\pytorch_1579082406639\work\aten\src\ATen/native/IndexingUtils.h:20)
Warning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (expandTensors at C:\w\1\s\tmp_conda_3.6_095855\conda\conda-bld\pytorch_1579082406639\work\aten\src\ATen/native/IndexingUtils.h:20)
Warning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (expandTensors at C:\w\1\s\tmp_conda_3.6_095855\conda\conda-bld\pytorch_1579082406639\work\aten\src\ATen/native/IndexingUtils.h:20)
Warning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (expandTensors at C:\w\1\s\tmp_conda_3.6_095855\conda\conda-bld\pytorch_1579082406639\work\aten\src\ATen/native/IndexingUtils.h:20)
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Continuum\anaconda2\envs\torch_gpu\lib\site-packages\torch\utils\data\_utils\worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\xxx\AppData\Local\Continuum\anaconda2\envs\torch_gpu\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\xxx\AppData\Local\Continuum\anaconda2\envs\torch_gpu\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "G:\Projects\1-stage-wseg\datasets\pascal_voc.py", line 175, in __getitem__
    labels[unique_labels] = 1
IndexError: The shape of the mask [2] at index 0 does not match the shape of the indexed tensor [20] at index 0

Could you shed some light on this?

**Comment by wangtuo0820** [comment]
> I met a similar issue with running the script 'run_voc_resnet38.sh'.
> 
> Traceback (most recent call last):
> File "G:/Projects/1-stage-wseg/train.py", line 334, in
> time_call(trainer.validation, "Validation / Train: ", epoch, trainer.writer, trainer.trainloader_val)
> File "G:/Projects/1-stage-wseg/train.py", line 324, in time_call
> func(*args, **kwargs)
> File "G:/Projects/1-stage-wseg/train.py", line 245, in validation
> for n, (image, gt_labels, _) in enumerate(loader):
> File "C:\Users\xxx\AppData\Local\Continuum\anaconda2\envs\torch_gpu\lib\site-packages\torch\utils\data\dataloader.py", line 345, in **next**
> Warning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (expandTensors at C:\w\1\s\tmp_conda_3.6_095855\conda\conda-bld\pytorch_1579082406639\work\aten\src\ATen/native/IndexingUtils.h:20)
> data = self._next_data()
> File "C:\Users\xxx\AppData\Local\Continuum\anaconda2\envs\torch_gpu\lib\site-packages\torch\utils\data\dataloader.py", line 856, in _next_data
> return self._process_data(data)
> File "C:\Users\xxx\AppData\Local\Continuum\anaconda2\envs\torch_gpu\lib\site-packages\torch\utils\data\dataloader.py", line 881, in _process_data
> data.reraise()
> File "C:\Users\xxx\AppData\Local\Continuum\anaconda2\envs\torch_gpu\lib\site-packages\torch_utils.py", line 394, in reraise
> Warning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (expandTensors at C:\w\1\s\tmp_conda_3.6_095855\conda\conda-bld\pytorch_1579082406639\work\aten\src\ATen/native/IndexingUtils.h:20)
> Warning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (expandTensors at C:\w\1\s\tmp_conda_3.6_095855\conda\conda-bld\pytorch_1579082406639\work\aten\src\ATen/native/IndexingUtils.h:20)
> Warning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (expandTensors at C:\w\1\s\tmp_conda_3.6_095855\conda\conda-bld\pytorch_1579082406639\work\aten\src\ATen/native/IndexingUtils.h:20)
> Warning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (expandTensors at C:\w\1\s\tmp_conda_3.6_095855\conda\conda-bld\pytorch_1579082406639\work\aten\src\ATen/native/IndexingUtils.h:20)
> Warning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (expandTensors at C:\w\1\s\tmp_conda_3.6_095855\conda\conda-bld\pytorch_1579082406639\work\aten\src\ATen/native/IndexingUtils.h:20)
> Warning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (expandTensors at C:\w\1\s\tmp_conda_3.6_095855\conda\conda-bld\pytorch_1579082406639\work\aten\src\ATen/native/IndexingUtils.h:20)
> Warning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (expandTensors at C:\w\1\s\tmp_conda_3.6_095855\conda\conda-bld\pytorch_1579082406639\work\aten\src\ATen/native/IndexingUtils.h:20)
> raise self.exc_type(msg)
> IndexError: Caught IndexError in DataLoader worker process 0.
> Original Traceback (most recent call last):
> File "C:\Users\xxx\AppData\Local\Continuum\anaconda2\envs\torch_gpu\lib\site-packages\torch\utils\data_utils\worker.py", line 178, in _worker_loop
> data = fetcher.fetch(index)
> File "C:\Users\xxx\AppData\Local\Continuum\anaconda2\envs\torch_gpu\lib\site-packages\torch\utils\data_utils\fetch.py", line 44, in fetch
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "C:\Users\xxx\AppData\Local\Continuum\anaconda2\envs\torch_gpu\lib\site-packages\torch\utils\data_utils\fetch.py", line 44, in
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "G:\Projects\1-stage-wseg\datasets\pascal_voc.py", line 175, in **getitem**
> labels[unique_labels] = 1
> IndexError: The shape of the mask [2] at index 0 does not match the shape of the indexed tensor [20] at index 0
> 
> Could you shed some light on this?

It seems to be related with the numpy version. i added `unique_labels = unique_labels.tolist() ` on line 175. After that, the error was fixed. My numpy version is 1.18.5. i hope that could be useful for you.

**Comment by arnike** [comment]
@wangtuo0820, thanks. Could you also tell me your PyTorch version?

**Comment by wangtuo0820** [comment]
> @wangtuo0820, thanks. Could you also tell me your PyTorch version?

1.2.0
